"""Render reviewed findings from computed results; --check detects stale documents."""
import argparse
from pathlib import Path
from src.analyze_game_data import load_data,project_root
from src.analyze_monetization import (prepare_sales,monetization_window_summary,bm_evaluation_summary,
    adjacent_product_summary,revenue_decomposition)
from src.analyze_incident import (incident_window_summary,incident_stage_evaluation,incident_retention_summary,
    incident_final_evaluation)
from src.analyze_lifecycle import event_dependency_summary,lifecycle_event_performance
from src.analyze_retention import retention_monthly_summary,regional_quality_summary,acquisition_quality_comparison
from src.analyze_pve import prepare_boss_funnel,boss_regional_summary,boss_performance_summary
from src.analyze_regional import regional_evidence_summary,regional_guardrail_matrix,regional_action_plan
from src.analyze_sensitivity import sensitivity_tables
import pandas as pd


def table(frame,columns=None):
    frame=frame[columns] if columns else frame
    def fmt(v):
        if pd.isna(v):return '—'
        if isinstance(v,float):return f'{v:,.2f}'
        return str(v).replace('|','/').replace('\n',' ')
    return '\n'.join(['| '+' | '.join(frame.columns)+' |','| '+' | '.join(['---']*len(frame.columns))+' |']+
        ['| '+' | '.join(fmt(v) for v in row)+' |' for row in frame.itertuples(index=False,name=None)])


def render():
    d,r,e,p,s,b=load_data(project_root());sales=prepare_sales(s,p)
    w=monetization_window_summary(d,sales);bm=bm_evaluation_summary(w,r)
    adj=adjacent_product_summary(d,sales);dec=revenue_decomposition(w)
    iw=incident_window_summary(d);st=incident_stage_evaluation(iw)
    ir=incident_retention_summary(r);final=incident_final_evaluation(st,ir)
    monthly=retention_monthly_summary(r,e);acq=acquisition_quality_comparison(r,monthly)
    boss=boss_performance_summary(prepare_boss_funnel(b,d))
    collab=pd.concat([regional_quality_summary(monthly,k) for k in ['fantasy_crossover_2024','astra_crossover_2025']])
    ev=regional_evidence_summary(event_dependency_summary(d),collab,boss_regional_summary(prepare_boss_funnel(b,d)),bm,final)
    guard=regional_guardrail_matrix(ev);actions=regional_action_plan(ev)
    payer,base=sensitivity_tables()
    bg=bm.set_index('scope').loc['ALL'];wg=w[w.scope.eq('ALL')]
    pre=wg.set_index('window').loc['local_baseline'];launch=wg.set_index('window').loc['launch']
    header='<!-- Generated by python -m src.build_evidence; edit the renderer, then regenerate. -->\n'
    adj_idx = adj.set_index('product_name')
    bm_idx = bm.set_index('scope')

    doc4=f'''# Analysis 4: Revenue Growth and Subscription Value

> This analysis uses synthetic scenario data. Paying-user counts are service-level daily values, not deduplicated monthly users.

## Summary

Revenue increased strongly after the PvE Growth Subscription launched, but adjacent offers weakened on a revenue-per-payer basis.

The subscription contributed part of the total increase, while most of the revenue lift came from the existing product catalog. This suggests the launch increased overall revenue but may also have shifted spending across offers.

## Method

| Rule | Definition |
|---|---|
| Baseline | 2025-04-15 to 2025-05-14 |
| Launch | 2025-05-15 to 2025-06-14 |
| Post-launch | 2025-06-15 to 2025-06-28 |
| Revenue threshold | +10% |
| Paying-user threshold | +5% |
| Adjacent-offer warning | -5% revenue per payer-day |
| D30 warning | -1.0 pp vs February |

February is kept as a secondary historical reference.

## 1. Revenue and payer growth

![Revenue bridge](../../images/bm_revenue_decomposition.png)

| Metric | Baseline | Launch |
|---|---:|---:|
| Paying users per day | {pre.pu_per_day:,.2f} | {launch.pu_per_day:,.2f} |
| Conversion rate | {pre.conversion_rate*100:.2f}% | {launch.conversion_rate*100:.2f}% |
| Revenue per service payer-day | ${pre.revenue_per_payer_day:.2f} | ${launch.revenue_per_payer_day:.2f} |

Revenue per day increased by {bg.launch_revenue_per_day_change_pct:.2f}%, while paying users per day increased by {bg.launch_pu_per_day_change_pct:.2f}%.

The new subscription contributed about 25% of the total revenue increase. Most of the lift came from higher revenue in existing products.

## 2. Adjacent offers

![Adjacent offers](../../images/adjacent_product_cannibalization.png)

| Product | Launch change | Post-launch change |
|---|---:|---:|
| Monthly Mission Pass | {adj_idx.loc['Monthly Mission Pass','launch_change_pct']:.2f}% | {adj_idx.loc['Monthly Mission Pass','post_14_change_pct']:.2f}% |
| 30-Day Premium Currency Pass | {adj_idx.loc['30-Day Premium Currency Pass','launch_change_pct']:.2f}% | {adj_idx.loc['30-Day Premium Currency Pass','post_14_change_pct']:.2f}% |
| Account Growth Booster | {adj_idx.loc['Account Growth Booster','launch_change_pct']:.2f}% | {adj_idx.loc['Account Growth Booster','post_14_change_pct']:.2f}% |
| Combined adjacent set | {bg.adjacent_launch_revenue_per_payer_day_change_pct:.2f}% | {bg.adjacent_post_14_revenue_per_payer_day_change_pct:.2f}% |

All three adjacent offers fell below the -5% warning threshold on a revenue-per-payer basis.

However, their absolute revenue per day was still above baseline after launch. This means the data suggests a change in spending mix, not an overall collapse in those products.

## 3. Regional results

![Regional checks](../../images/bm_regional_guardrails.png)

| Region | Revenue change | Paying-user change | Adjacent post-launch change |
|---|---:|---:|---:|
| KR | {bm_idx.loc['KR','launch_revenue_per_day_change_pct']:.2f}% | {bm_idx.loc['KR','launch_pu_per_day_change_pct']:.2f}% | {bm_idx.loc['KR','adjacent_post_14_revenue_per_payer_day_change_pct']:.2f}% |
| JP | {bm_idx.loc['JP','launch_revenue_per_day_change_pct']:.2f}% | {bm_idx.loc['JP','launch_pu_per_day_change_pct']:.2f}% | {bm_idx.loc['JP','adjacent_post_14_revenue_per_payer_day_change_pct']:.2f}% |
| Global West | {bm_idx.loc['GLOBAL_WEST','launch_revenue_per_day_change_pct']:.2f}% | {bm_idx.loc['GLOBAL_WEST','launch_pu_per_day_change_pct']:.2f}% | {bm_idx.loc['GLOBAL_WEST','adjacent_post_14_revenue_per_payer_day_change_pct']:.2f}% |

The same pattern appears in all three regions: overall revenue and payer counts increased, while adjacent-offer revenue per payer declined.

Global West shows the largest change in both directions.

## Validation note

During validation, service-level paying-user counts were corrected so they stayed within valid product-level buyer limits. Revenue and sales data did not change.

See [validation changes](../validation_changes.md) for details.

## Next step

Collect user-level purchase and subscription data to check whether the same users moved spending between offers.

Analysis 5 looks at how activity and revenue recovered after the service incident.
'''
    stage=iw[iw.scope.eq('ALL')].copy();stage['revenue_per_payer_day_index']=stage['revenue_per_payer_day_recovery_index']
    ir_display=ir[ir.scope.eq('ALL')].copy()
    ir_display['d30_retention_pct']=ir_display.d30_retention*100
    stage_idx = stage.set_index('window')
    final_idx = final.set_index('scope')
    ir_idx = ir_display.set_index('period')

    doc5=f'''# Analysis 5: Incident and Recovery

> This analysis uses synthetic scenario data. Recovery indices compare each recovery stage with the pre-incident reference.

## Summary

User activity recovered faster than commercial metrics after the outage.

During the compensation period, returned users reached {stage_idx.loc['extraordinary_compensation','returned_users_recovery_index']:.2f}% of the pre-incident baseline, while revenue recovered to {stage_idx.loc['extraordinary_compensation','revenue_recovery_index']:.2f}%. By late September, DAU, paying users and revenue had returned close to their reference levels, but later D30 retention remained below the pre-incident cohort.

## Method

| Rule | Definition |
|---|---|
| Pre-incident reference | 2025-07-31 to 2025-08-11 |
| DAU recovery target | 95 |
| Paying-user recovery target | 90 |
| Revenue recovery target | 90 |
| D30 warning | below -0.5 pp vs June reference |

A recovery index of 100 matches the pre-incident reference.

## 1. Daily recovery

![Daily recovery](../../images/incident_daily_recovery_by_region.png)

| Stage | DAU index | Paying-user index | Revenue index | Returned-user index |
|---|---:|---:|---:|---:|
| Pre-incident baseline | {stage_idx.loc['pre_incident_baseline','dau_recovery_index']:.2f} | {stage_idx.loc['pre_incident_baseline','pu_recovery_index']:.2f} | {stage_idx.loc['pre_incident_baseline','revenue_recovery_index']:.2f} | {stage_idx.loc['pre_incident_baseline','returned_users_recovery_index']:.2f} |
| Full outage | {stage_idx.loc['full_outage','dau_recovery_index']:.2f} | {stage_idx.loc['full_outage','pu_recovery_index']:.2f} | {stage_idx.loc['full_outage','revenue_recovery_index']:.2f} | {stage_idx.loc['full_outage','returned_users_recovery_index']:.2f} |
| Partial restoration | {stage_idx.loc['partial_restoration','dau_recovery_index']:.2f} | {stage_idx.loc['partial_restoration','pu_recovery_index']:.2f} | {stage_idx.loc['partial_restoration','revenue_recovery_index']:.2f} | {stage_idx.loc['partial_restoration','returned_users_recovery_index']:.2f} |
| Delayed response | {stage_idx.loc['delayed_response','dau_recovery_index']:.2f} | {stage_idx.loc['delayed_response','pu_recovery_index']:.2f} | {stage_idx.loc['delayed_response','revenue_recovery_index']:.2f} | {stage_idx.loc['delayed_response','returned_users_recovery_index']:.2f} |
| Compensation | {stage_idx.loc['extraordinary_compensation','dau_recovery_index']:.2f} | {stage_idx.loc['extraordinary_compensation','pu_recovery_index']:.2f} | {stage_idx.loc['extraordinary_compensation','revenue_recovery_index']:.2f} | {stage_idx.loc['extraordinary_compensation','returned_users_recovery_index']:.2f} |
| Remediation | {stage_idx.loc['postmortem_remediation','dau_recovery_index']:.2f} | {stage_idx.loc['postmortem_remediation','pu_recovery_index']:.2f} | {stage_idx.loc['postmortem_remediation','revenue_recovery_index']:.2f} | {stage_idx.loc['postmortem_remediation','returned_users_recovery_index']:.2f} |
| Late September | {stage_idx.loc['residual_post_recovery','dau_recovery_index']:.2f} | {stage_idx.loc['residual_post_recovery','pu_recovery_index']:.2f} | {stage_idx.loc['residual_post_recovery','revenue_recovery_index']:.2f} | {stage_idx.loc['residual_post_recovery','returned_users_recovery_index']:.2f} |

Activity recovered first. Compensation produced a large return spike, but payment and revenue recovery remained much lower during the same period.

![Commercial recovery](../../images/incident_reactivation_commercial_bridge.png)

This shows why technical recovery, user return and commercial recovery should be tracked separately.

## 2. Regional recovery

The regional results below use the late-September recovery stage, with D30 compared against the June reference cohort.

![Regional exits](../../images/incident_regional_exit_guardrails.png)

| Region | DAU index | Paying-user index | Revenue index | D30 change |
|---|---:|---:|---:|---:|
| KR | {final_idx.loc['KR','dau_recovery_index']:.2f} | {final_idx.loc['KR','pu_recovery_index']:.2f} | {final_idx.loc['KR','revenue_recovery_index']:.2f} | {final_idx.loc['KR','d30_change_pp']:.2f} pp |
| JP | {final_idx.loc['JP','dau_recovery_index']:.2f} | {final_idx.loc['JP','pu_recovery_index']:.2f} | {final_idx.loc['JP','revenue_recovery_index']:.2f} | {final_idx.loc['JP','d30_change_pp']:.2f} pp |
| Global West | {final_idx.loc['GLOBAL_WEST','dau_recovery_index']:.2f} | {final_idx.loc['GLOBAL_WEST','pu_recovery_index']:.2f} | {final_idx.loc['GLOBAL_WEST','revenue_recovery_index']:.2f} | {final_idx.loc['GLOBAL_WEST','d30_change_pp']:.2f} pp |

All three regions recovered the daily operational metrics by late September.

However, D30 retention remained below the June reference in every region, with the largest gap in Global West.

## 3. Post-incident D30

![Mature cohorts](../../images/incident_d30_recovery_by_region.png)

| Cohort | D30 retention | Change vs June |
|---|---:|---:|
| June reference | {ir_idx.loc['june_reference','d30_retention_pct']:.2f}% | {ir_idx.loc['june_reference','d30_change_pp']:.2f} pp |
| July | {ir_idx.loc['july_overlap','d30_retention_pct']:.2f}% | {ir_idx.loc['july_overlap','d30_change_pp']:.2f} pp |
| August | {ir_idx.loc['august_incident','d30_retention_pct']:.2f}% | {ir_idx.loc['august_incident','d30_change_pp']:.2f} pp |
| September | {ir_idx.loc['september_remediation','d30_retention_pct']:.2f}% | {ir_idx.loc['september_remediation','d30_change_pp']:.2f} pp |
| October | {ir_idx.loc['october_residual','d30_retention_pct']:.2f}% | {ir_idx.loc['october_residual','d30_change_pp']:.2f} pp |
| November | {ir_idx.loc['november_residual','d30_retention_pct']:.2f}% | {ir_idx.loc['november_residual','d30_change_pp']:.2f} pp |

Later cohorts improved from the August low, but October and November still remained below the June reference.

These are new acquisition cohorts, so they do not show whether the same incident-affected users fully recovered.

## Next step

Close the daily incident response only after activity, payer and revenue targets recover. Continue retention monitoring separately.

For future incidents, connect outage exposure, compensation, return and payment activity at the user level.
'''
    doc6=header+'''# Analysis 6: Regional Decisions

## Decision

Use shared measurement and reversible tests, then prioritize regional diagnostics.
The original JP-only launch-warning claim is withdrawn after the payer audit:
all regions breach both launch and post-14 adjacent-offer guardrails. No composite
score combines revenue, retention points and participation indices.

## Evidence

![Regional evidence](../../images/regional_cross_analysis_evidence.png)

'''+table(ev,['region','fantasy_d30_change_pp','astra_d30_change_pp','astra_normal_participation_index','bm_launch_revenue_change_pct','bm_adjacent_launch_change_pct','bm_adjacent_post_14_change_pct','incident_nru_recovery_index','incident_d30_change_pp'])+'''

Within this synthetic comparison, KR has the lowest NRU reference index, so acquisition mix is an investigation
priority; channel causes and CAC are unobserved. JP has the largest Fantasy-context D30 checkpoint difference in this scenario, but no longer has a unique offer-warning mechanism. Global West
combines the strongest launch-revenue response with the largest launch adjacency
and later new-cohort D30 checkpoint gaps; additional spend should await quality diagnostics.

## Guardrails

![Guardrails](../../images/regional_guardrail_matrix.png)

'''+table(guard,['guardrail_label','region','value','status'])+'''

Equality semantics match source analyses: D30 at -1 pp and adjacency at -5%
are warnings; entry at 90 and residual D30 at -0.5 pp pass. Five checks warn in
all regions under the published payer assumption; daily operational exits pass.
These authored thresholds are not industry standards or statistical significance.

## Actions

'''+table(actions,['scope','priority','theme','action','evidence'])+'''

Low boss entry plus normal participant outcomes supports an entry hypothesis;
it does not locate individual dropout or rule out power-based selection.
Likewise, service-cohort D30 does not trace incident survivors. Follow the
[decision plan](../decision_plan.md), including telemetry, experimental unit,
primary outcome, guardrails and the decision that would change.
'''
    docsen=header+'''# Sensitivity to Baselines and Payer Assumptions

## Payer overlap is not identified

For each date-region, a feasible union lies between maximum(product purchasers)
and min(DAU, sum(product purchasers)). The published rule caps the original demand
target to that interval. Alternative extremes below are not estimates of real
buyer overlap. Even a feasible synthetic payer count does not validate behavior.

'''+table(payer,['scope','payer_assumption','launch_pu_per_day_change_pct','adjacent_launch_revenue_per_payer_day_change_pct','adjacent_post_14_revenue_per_payer_day_change_pct','outcome'])+'''

## Baseline choice changes magnitude

Seven, fourteen and twenty-eight day references are shown without silently
removing unfavorable event overlaps. Incident references end before the outage.
The primary operational baseline remains the 12 clean days in the specification.

'''+table(base,['context','baseline_days','baseline_start','baseline_end','overlaps','metric','change_pct'])+'''

These checks test stability under alternative assumptions. They are not causal
controls or uncertainty intervals. Generated rates were authored rather than
estimated from independent user observations, so inferential claims would add
false precision. A real deployment needs assignment/exposure logs, a planned
minimum detectable effect and dependence-aware analysis.
'''
    claims=[]
    def add(name,value):claims.append({'metric':name,'value':float(value)})
    life=lifecycle_event_performance(d,e);ann=life[life.event_name.eq('First Anniversary')].iloc[0]
    add('anniversary_dau_change_pct',ann.dau_during_change_pct)
    add('anniversary_post14_dau_change_pct',ann.dau_post_14_change_pct)
    for row in acq.itertuples():
        add(row.comparison_id+'_cohort_change_pct',row.cohort_size_change_pct)
        add(row.comparison_id+'_d30_change_pp',row.d30_retention_change_pp)
    add('astra_normal_participation_index',boss.query("boss_id=='BOSS004' and difficulty=='NORMAL'").participation_benchmark_index.iloc[0])
    add('subscription_revenue_change_pct',bg.launch_revenue_per_day_change_pct)
    add('subscription_pu_change_pct',bg.launch_pu_per_day_change_pct)
    add('adjacent_post14_change_pct',bg.adjacent_post_14_revenue_per_payer_day_change_pct)
    comp=iw.query("scope=='ALL' and window=='extraordinary_compensation'").iloc[0]
    add('compensation_returned_index',comp.returned_users_recovery_index)
    add('compensation_revenue_index',comp.revenue_recovery_index)
    add('residual_d30_change_pp',final.set_index('scope').loc['ALL','d30_change_pp'])
    scope = '\n> All figures are synthetic scenario comparisons. Legacy D30 means a nested checkpoint proxy, not session-based exact-day retention. Recovery indices compare reference windows, not matched individual outcomes or trust.\n\n'
    doc4 = doc4.replace('\n\n', '\n'+scope, 1)
    doc5 = doc5.replace('\n\n', '\n'+scope, 1)
    doc6 = doc6.replace('\n\n', '\n'+scope, 1)
    return {'docs/findings/analysis_04_monetization.md':doc4,'docs/findings/analysis_05_incident.md':doc5,
        'docs/findings/analysis_06_regional_strategy.md':doc6,'docs/sensitivity.md':docsen,
        'docs/verified_claims.md':header+'# Recomputed headline claims\n\nSource: the checked-in six CSVs. Rebuild with `python -m src.build_evidence`.\n\n'+table(pd.DataFrame(claims))+'\n'}


def main(check=False):
    for filename,content in render().items():
        path=project_root()/filename
        if check:
            if not path.exists() or path.read_text()!=content:raise ValueError(f'Stale evidence: {filename}')
        else:path.write_text(content)
    print('Evidence documents match computed results' if check else 'Evidence documents regenerated')

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true')
    main(parser.parse_args().check)
