"""Render reviewed findings from computed results; --check detects stale documents."""
import argparse
from src.analyze_game_data import load_data,project_root
from src.analyze_monetization import (prepare_sales,monetization_window_summary,bm_evaluation_summary,
    adjacent_product_summary)
from src.analyze_incident import (incident_window_summary,incident_stage_evaluation,incident_retention_summary,
    incident_final_evaluation)
from src.analyze_lifecycle import event_dependency_summary,lifecycle_event_performance
from src.analyze_retention import retention_monthly_summary,regional_quality_summary,acquisition_quality_comparison
from src.analyze_pve import prepare_boss_funnel,boss_regional_summary,boss_performance_summary
from src.analyze_regional import regional_evidence_summary
from src.analyze_sensitivity import sensitivity_tables
import pandas as pd


def table(frame,columns=None):
    frame=frame[columns] if columns else frame
    def fmt(v):
        if pd.isna(v):return '—'
        if isinstance(v,float):return f'{v:,.2f}'
        return str(v).replace('|','/').replace('\n',' ')
    return '\n'.join(['| '+' | '.join(frame.columns)+' |','| '+' | '.join(['---']*len(frame.columns))+' |']+
        ['| '+' | '.join(fmt(v) for v in row)+' |' for row in frame.itertuples(index=False,name=None)])


def render():
    d,r,e,p,s,b=load_data(project_root());sales=prepare_sales(s,p)
    w=monetization_window_summary(d,sales);bm=bm_evaluation_summary(w,r)
    adj=adjacent_product_summary(d,sales);
    iw=incident_window_summary(d);st=incident_stage_evaluation(iw)
    ir=incident_retention_summary(r);final=incident_final_evaluation(st,ir)
    monthly=retention_monthly_summary(r,e);acq=acquisition_quality_comparison(r,monthly)
    boss=boss_performance_summary(prepare_boss_funnel(b,d))
    collab=pd.concat([regional_quality_summary(monthly,k) for k in ['fantasy_crossover_2024','astra_crossover_2025']])
    ev=regional_evidence_summary(event_dependency_summary(d),collab,boss_regional_summary(prepare_boss_funnel(b,d)),bm,final)
    payer,base=sensitivity_tables()
    bg=bm.set_index('scope').loc['ALL'];wg=w[w.scope.eq('ALL')]
    pre=wg.set_index('window').loc['local_baseline'];launch=wg.set_index('window').loc['launch']
    header='<!-- Generated by python -m src.build_evidence; edit the renderer, then regenerate. -->\n'
    adj_idx = adj.set_index('product_name')
    bm_idx = bm.set_index('scope')

    doc4=f'''# Analysis 4: Revenue Growth and Subscription Value

> This analysis uses synthetic scenario data. Paying-user counts are service-level daily values, not deduplicated monthly users.

## Summary

Revenue increased strongly after the PvE Growth Subscription launched, but adjacent offers weakened on a revenue-per-payer basis.

The subscription contributed part of the total increase, while most of the revenue lift came from the existing product catalog. This suggests the launch increased overall revenue but may also have shifted spending across offers.

## Method

| Rule | Definition |
|---|---|
| Baseline | 2025-04-15 to 2025-05-14 |
| Launch | 2025-05-15 to 2025-06-14 |
| Post-launch | 2025-06-15 to 2025-06-28 |
| Revenue threshold | +10% |
| Paying-user threshold | +5% |
| Adjacent-offer warning | -5% revenue per payer-day |
| D30 warning | -1.0 pp vs February |

February is kept as a secondary historical reference.

## 1. Revenue and payer growth

![Revenue bridge](../../images/bm_revenue_decomposition.png)

| Metric | Baseline | Launch |
|---|---:|---:|
| Paying users per day | {pre.pu_per_day:,.2f} | {launch.pu_per_day:,.2f} |
| Conversion rate | {pre.conversion_rate*100:.2f}% | {launch.conversion_rate*100:.2f}% |
| Revenue per service payer-day | ${pre.revenue_per_payer_day:.2f} | ${launch.revenue_per_payer_day:.2f} |

Revenue per day increased by {bg.launch_revenue_per_day_change_pct:.2f}%, while paying users per day increased by {bg.launch_pu_per_day_change_pct:.2f}%.

The new subscription contributed about 25% of the total revenue increase. Most of the lift came from higher revenue in existing products.

## 2. Adjacent offers

![Adjacent offers](../../images/adjacent_product_cannibalization.png)

| Product | Launch change | Post-launch change |
|---|---:|---:|
| Monthly Mission Pass | {adj_idx.loc['Monthly Mission Pass','launch_change_pct']:+.2f}% | {adj_idx.loc['Monthly Mission Pass','post_14_change_pct']:+.2f}% |
| 30-Day Premium Currency Pass | {adj_idx.loc['30-Day Premium Currency Pass','launch_change_pct']:+.2f}% | {adj_idx.loc['30-Day Premium Currency Pass','post_14_change_pct']:+.2f}% |
| Account Growth Booster | {adj_idx.loc['Account Growth Booster','launch_change_pct']:+.2f}% | {adj_idx.loc['Account Growth Booster','post_14_change_pct']:+.2f}% |
| Combined adjacent set | {bg.adjacent_launch_revenue_per_payer_day_change_pct:+.2f}% | {bg.adjacent_post_14_revenue_per_payer_day_change_pct:+.2f}% |

All three adjacent offers fell below the -5% warning threshold on a revenue-per-payer basis.

However, their absolute revenue per day was still above baseline after launch. This means the data suggests a change in spending mix, not an overall collapse in those products.

## 3. Regional results

![Regional checks](../../images/bm_regional_guardrails.png)

| Region | Revenue change | Paying-user change | Adjacent post-launch change |
|---|---:|---:|---:|
| KR | {bm_idx.loc['KR','launch_revenue_per_day_change_pct']:+.2f}% | {bm_idx.loc['KR','launch_pu_per_day_change_pct']:+.2f}% | {bm_idx.loc['KR','adjacent_post_14_revenue_per_payer_day_change_pct']:+.2f}% |
| JP | {bm_idx.loc['JP','launch_revenue_per_day_change_pct']:+.2f}% | {bm_idx.loc['JP','launch_pu_per_day_change_pct']:+.2f}% | {bm_idx.loc['JP','adjacent_post_14_revenue_per_payer_day_change_pct']:+.2f}% |
| Global West | {bm_idx.loc['GLOBAL_WEST','launch_revenue_per_day_change_pct']:+.2f}% | {bm_idx.loc['GLOBAL_WEST','launch_pu_per_day_change_pct']:+.2f}% | {bm_idx.loc['GLOBAL_WEST','adjacent_post_14_revenue_per_payer_day_change_pct']:+.2f}% |

The same pattern appears in all three regions: overall revenue and payer counts increased, while adjacent-offer revenue per payer declined.

Global West shows the largest change in both directions.

## Validation note

During validation, service-level paying-user counts were corrected so they stayed within valid product-level buyer limits. Revenue and sales data did not change.

See [validation changes](../validation_changes.md) for details.

## Next step

Collect user-level purchase and subscription data to check whether the same users moved spending between offers.

Analysis 5 looks at how activity and revenue recovered after the service incident.
'''
    stage=iw[iw.scope.eq('ALL')].copy();stage['revenue_per_payer_day_index']=stage['revenue_per_payer_day_recovery_index']
    ir_display=ir[ir.scope.eq('ALL')].copy()
    ir_display['d30_retention_pct']=ir_display.d30_retention*100
    stage_idx = stage.set_index('window')
    final_idx = final.set_index('scope')
    ir_idx = ir_display.set_index('period')

    doc5=f'''# Analysis 5: Incident and Recovery

> This analysis uses synthetic scenario data. Recovery indices compare each recovery stage with the pre-incident reference.

## Summary

User activity recovered faster than commercial metrics after the outage.

During the compensation period, returned users reached {stage_idx.loc['extraordinary_compensation','returned_users_recovery_index']:+.2f}% of the pre-incident baseline, while revenue recovered to {stage_idx.loc['extraordinary_compensation','revenue_recovery_index']:+.2f}%. By late September, DAU, paying users and revenue had returned close to their reference levels, but later D30 retention remained below the pre-incident cohort.

## Method

| Rule | Definition |
|---|---|
| Pre-incident reference | 2025-07-31 to 2025-08-11 |
| DAU recovery target | 95 |
| Paying-user recovery target | 90 |
| Revenue recovery target | 90 |
| D30 warning | below -0.5 pp vs June reference |

A recovery index of 100 matches the pre-incident reference.

## 1. Daily recovery

![Daily recovery](../../images/incident_daily_recovery_by_region.png)

| Stage | DAU index | Paying-user index | Revenue index | Returned-user index |
|---|---:|---:|---:|---:|
| Pre-incident baseline | {stage_idx.loc['pre_incident_baseline','dau_recovery_index']:.2f} | {stage_idx.loc['pre_incident_baseline','pu_recovery_index']:.2f} | {stage_idx.loc['pre_incident_baseline','revenue_recovery_index']:.2f} | {stage_idx.loc['pre_incident_baseline','returned_users_recovery_index']:+.2f} |
| Full outage | {stage_idx.loc['full_outage','dau_recovery_index']:+.2f} | {stage_idx.loc['full_outage','pu_recovery_index']:+.2f} | {stage_idx.loc['full_outage','revenue_recovery_index']:+.2f} | {stage_idx.loc['full_outage','returned_users_recovery_index']:+.2f} |
| Partial restoration | {stage_idx.loc['partial_restoration','dau_recovery_index']:+.2f} | {stage_idx.loc['partial_restoration','pu_recovery_index']:+.2f} | {stage_idx.loc['partial_restoration','revenue_recovery_index']:+.2f} | {stage_idx.loc['partial_restoration','returned_users_recovery_index']:+.2f} |
| Delayed response | {stage_idx.loc['delayed_response','dau_recovery_index']:+.2f} | {stage_idx.loc['delayed_response','pu_recovery_index']:+.2f} | {stage_idx.loc['delayed_response','revenue_recovery_index']:+.2f} | {stage_idx.loc['delayed_response','returned_users_recovery_index']:+.2f} |
| Compensation | {stage_idx.loc['extraordinary_compensation','dau_recovery_index']:+.2f} | {stage_idx.loc['extraordinary_compensation','pu_recovery_index']:+.2f} | {stage_idx.loc['extraordinary_compensation','revenue_recovery_index']:+.2f} | {stage_idx.loc['extraordinary_compensation','returned_users_recovery_index']:+.2f} |
| Remediation | {stage_idx.loc['postmortem_remediation','dau_recovery_index']:+.2f} | {stage_idx.loc['postmortem_remediation','pu_recovery_index']:+.2f} | {stage_idx.loc['postmortem_remediation','revenue_recovery_index']:+.2f} | {stage_idx.loc['postmortem_remediation','returned_users_recovery_index']:+.2f} |
| Late September | {stage_idx.loc['residual_post_recovery','dau_recovery_index']:+.2f} | {stage_idx.loc['residual_post_recovery','pu_recovery_index']:+.2f} | {stage_idx.loc['residual_post_recovery','revenue_recovery_index']:+.2f} | {stage_idx.loc['residual_post_recovery','returned_users_recovery_index']:+.2f} |

Activity recovered first. Compensation produced a large return spike, but payment and revenue recovery remained much lower during the same period.

![Commercial recovery](../../images/incident_reactivation_commercial_bridge.png)

This shows why technical recovery, user return and commercial recovery should be tracked separately.

## 2. Regional recovery

The regional results below use the late-September recovery stage, with D30 compared against the June reference cohort.

![Regional exits](../../images/incident_regional_exit_guardrails.png)

| Region | DAU index | Paying-user index | Revenue index | D30 change |
|---|---:|---:|---:|---:|
| KR | {final_idx.loc['KR','dau_recovery_index']:.2f} | {final_idx.loc['KR','pu_recovery_index']:.2f} | {final_idx.loc['KR','revenue_recovery_index']:.2f} | {final_idx.loc['KR','d30_change_pp']:+.2f} pp |
| JP | {final_idx.loc['JP','dau_recovery_index']:.2f} | {final_idx.loc['JP','pu_recovery_index']:.2f} | {final_idx.loc['JP','revenue_recovery_index']:.2f} | {final_idx.loc['JP','d30_change_pp']:+.2f} pp |
| Global West | {final_idx.loc['GLOBAL_WEST','dau_recovery_index']:.2f} | {final_idx.loc['GLOBAL_WEST','pu_recovery_index']:.2f} | {final_idx.loc['GLOBAL_WEST','revenue_recovery_index']:.2f} | {final_idx.loc['GLOBAL_WEST','d30_change_pp']:+.2f} pp |

All three regions recovered the daily operational metrics by late September.

However, D30 retention remained below the June reference in every region, with the largest gap in Global West.

## 3. Post-incident D30

![Mature cohorts](../../images/incident_d30_recovery_by_region.png)

| Cohort | D30 retention | Change vs June |
|---|---:|---:|
| June reference | {ir_idx.loc['june_reference','d30_retention_pct']:+.2f}% | {ir_idx.loc['june_reference','d30_change_pp']:+.2f} pp |
| July | {ir_idx.loc['july_overlap','d30_retention_pct']:+.2f}% | {ir_idx.loc['july_overlap','d30_change_pp']:+.2f} pp |
| August | {ir_idx.loc['august_incident','d30_retention_pct']:+.2f}% | {ir_idx.loc['august_incident','d30_change_pp']:+.2f} pp |
| September | {ir_idx.loc['september_remediation','d30_retention_pct']:+.2f}% | {ir_idx.loc['september_remediation','d30_change_pp']:+.2f} pp |
| October | {ir_idx.loc['october_residual','d30_retention_pct']:+.2f}% | {ir_idx.loc['october_residual','d30_change_pp']:+.2f} pp |
| November | {ir_idx.loc['november_residual','d30_retention_pct']:+.2f}% | {ir_idx.loc['november_residual','d30_change_pp']:+.2f} pp |

Later cohorts improved from the August low, but October and November still remained below the June reference.

These are new acquisition cohorts, so they do not show whether the same incident-affected users fully recovered.

## Next step

Close the daily incident response only after activity, payer and revenue targets recover. Continue retention monitoring separately.

For future incidents, connect outage exposure, compensation, return and payment activity at the user level.
'''
    ev_idx = ev.set_index('region')

    doc6=f'''# Analysis 6: Regional Comparison

> This analysis uses synthetic scenario data and summarizes the main regional differences from Analyses 1–5.

## Summary

All three regions show the same broad risks: weaker Astra D30 retention, lower boss participation, and weaker adjacent-offer revenue per payer after the subscription launch.

The size of those changes differs by region. Global West shows the strongest subscription revenue growth but also the largest adjacent-offer decline and post-incident D30 gap. KR shows the weakest NRU recovery index, while JP shows the strongest Fantasy-context D30 improvement.

## Regional comparison

![Regional evidence](../../images/regional_cross_analysis_evidence.png)

| Region | Fantasy D30 | Astra D30 | Astra boss entry index | Subscription revenue | Adjacent post-launch | Post-incident D30 |
|---|---:|---:|---:|---:|---:|---:|
| KR | {ev_idx.loc['KR','fantasy_d30_change_pp']:+.2f} pp | {ev_idx.loc['KR','astra_d30_change_pp']:+.2f} pp | {ev_idx.loc['KR','astra_normal_participation_index']:.2f} | {ev_idx.loc['KR','bm_launch_revenue_change_pct']:+.2f}% | {ev_idx.loc['KR','bm_adjacent_post_14_change_pct']:+.2f}% | {ev_idx.loc['KR','incident_d30_change_pp']:+.2f} pp |
| JP | {ev_idx.loc['JP','fantasy_d30_change_pp']:+.2f} pp | {ev_idx.loc['JP','astra_d30_change_pp']:+.2f} pp | {ev_idx.loc['JP','astra_normal_participation_index']:.2f} | {ev_idx.loc['JP','bm_launch_revenue_change_pct']:+.2f}% | {ev_idx.loc['JP','bm_adjacent_post_14_change_pct']:+.2f}% | {ev_idx.loc['JP','incident_d30_change_pp']:+.2f} pp |
| Global West | {ev_idx.loc['GLOBAL_WEST','fantasy_d30_change_pp']:+.2f} pp | {ev_idx.loc['GLOBAL_WEST','astra_d30_change_pp']:+.2f} pp | {ev_idx.loc['GLOBAL_WEST','astra_normal_participation_index']:.2f} | {ev_idx.loc['GLOBAL_WEST','bm_launch_revenue_change_pct']:+.2f}% | {ev_idx.loc['GLOBAL_WEST','bm_adjacent_post_14_change_pct']:+.2f}% | {ev_idx.loc['GLOBAL_WEST','incident_d30_change_pp']:+.2f} pp |

## Shared findings

![Guardrails](../../images/regional_guardrail_matrix.png)

- Astra D30 retention is below the warning threshold in all three regions.
- Astra boss participation is below the reference threshold in all three regions.
- Adjacent-offer revenue per payer declines after subscription launch in all three regions.
- Daily operational metrics recover after the incident in all three regions.
- Post-incident D30 remains below the June reference in all three regions.

These shared patterns support common measurement and testing across regions before applying region-specific changes.

## Regional focus

**KR:** Check acquisition mix and boss-entry eligibility first. KR has the lowest NRU recovery index and a similar Astra entry gap to the other regions.

**JP:** Monitor offer differentiation and retention. JP has the strongest Fantasy-context D30 improvement, but still shows the same Astra entry and adjacent-offer warnings.

**Global West**: Review acquisition quality and offer mix before scaling further. It has the strongest subscription revenue growth, but also the largest adjacent-offer decline and post-incident D30 gap.

## Next step

Use the same core measurements across all three regions, then adjust experiments based on the regional differences above.

See the [decision plan](../decision_plan.md) for the proposed tests.
'''
    payer_display = payer.copy()

    payer_scope_order = ['ALL', 'KR', 'JP', 'GLOBAL_WEST']
    payer_assumption_order = [
        'published_feasible_union',
        'maximum_overlap',
        'no_overlap_capped_at_dau',
    ]

    payer_display['scope'] = pd.Categorical(
        payer_display['scope'],
        categories=payer_scope_order,
        ordered=True,
    )
    payer_display['payer_assumption'] = pd.Categorical(
        payer_display['payer_assumption'],
        categories=payer_assumption_order,
        ordered=True,
    )
    payer_display = payer_display.sort_values(
        ['payer_assumption', 'scope']
    ).copy()

    payer_display['scope'] = payer_display['scope'].astype(str).replace({
        'GLOBAL_WEST': 'Global West',
    })
    payer_display['payer_assumption'] = (
        payer_display['payer_assumption'].astype(str).replace({
            'published_feasible_union': 'Published',
            'maximum_overlap': 'Maximum overlap',
            'no_overlap_capped_at_dau': 'No overlap',
        })
    )

    baseline_pivot = base.pivot_table(
        index=['context', 'baseline_days', 'overlaps'],
        columns='metric',
        values='change_pct',
        aggfunc='first',
    ).reset_index()

    context_order = ['subscription', 'compensation']
    baseline_pivot['context'] = pd.Categorical(
        baseline_pivot['context'],
        categories=context_order,
        ordered=True,
    )
    baseline_pivot = baseline_pivot.sort_values(
        ['context', 'baseline_days']
    ).copy()

    baseline_pivot['Context'] = (
        baseline_pivot['context'].astype(str).str.capitalize()
    )
    baseline_pivot['Baseline'] = (
        baseline_pivot['baseline_days'].astype(int).astype(str) + ' days'
    )
    baseline_pivot['Overlap'] = baseline_pivot['overlaps'].fillna('None')

    docsen='''# Sensitivity Checks

## 1. Payer assumptions

Daily service PU is not based on individual buyer identities, so the exact overlap between product purchasers is unknown.

To check whether the main monetization finding depends on that assumption, I compared three valid payer-count scenarios:

- Published assumption
- Maximum buyer overlap
- No overlap, capped at DAU

| Scope | Payer assumption | PU change | Adjacent launch change | Adjacent post-launch change |
|---|---|---:|---:|---:|
''' + '\n'.join(
        f"| {row.scope} | {row.payer_assumption} | "
        f"{row.launch_pu_per_day_change_pct:+.2f}% | "
        f"{row.adjacent_launch_revenue_per_payer_day_change_pct:+.2f}% | "
        f"{row.adjacent_post_14_revenue_per_payer_day_change_pct:+.2f}% |"
        for row in payer_display.itertuples()
    ) + '''

The exact size changes, but the direction is stable: paying users increase while adjacent-offer revenue per payer declines.

## 2. Baseline length

I also compared 7-, 14- and 28-day baselines for the subscription and compensation periods.

| Context | Baseline | Overlap | DAU | PU | Revenue | Returned users |
|---|---:|---|---:|---:|---:|---:|
''' + '\n'.join(
        f"| {row.Context} | {row.Baseline} | {row.Overlap} | "
        f"{row.dau:+.2f}% | {row.pu:+.2f}% | "
        f"{row.revenue:+.2f}% | {row.returned_users:+.2f}% |"
        for row in baseline_pivot.itertuples()
    ) + '''

Baseline choice changes the size of the result, especially when longer windows include another event. The overall direction remains the same.

## Takeaway

These checks do not prove causal effects. They show that the main conclusions are not dependent on one payer assumption or one baseline length.

For a real service, user-level purchase, exposure and assignment data would be needed for stronger conclusions.
'''
    claims=[]
    def add(name,value):claims.append({'metric':name,'value':float(value)})
    life=lifecycle_event_performance(d,e);ann=life[life.event_name.eq('First Anniversary')].iloc[0]
    add('anniversary_dau_change_pct',ann.dau_during_change_pct)
    add('anniversary_post14_dau_change_pct',ann.dau_post_14_change_pct)
    for row in acq.itertuples():
        add(row.comparison_id+'_cohort_change_pct',row.cohort_size_change_pct)
        add(row.comparison_id+'_d30_change_pp',row.d30_retention_change_pp)
    add('astra_normal_participation_index',boss.query("boss_id=='BOSS004' and difficulty=='NORMAL'").participation_benchmark_index.iloc[0])
    add('subscription_revenue_change_pct',bg.launch_revenue_per_day_change_pct)
    add('subscription_pu_change_pct',bg.launch_pu_per_day_change_pct)
    add('adjacent_post14_change_pct',bg.adjacent_post_14_revenue_per_payer_day_change_pct)
    comp=iw.query("scope=='ALL' and window=='extraordinary_compensation'").iloc[0]
    add('compensation_returned_index',comp.returned_users_recovery_index)
    add('compensation_revenue_index',comp.revenue_recovery_index)
    add('residual_d30_change_pp',final.set_index('scope').loc['ALL','d30_change_pp'])
    scope = '\n> All figures are synthetic scenario comparisons. Legacy D30 means a nested checkpoint proxy, not session-based exact-day retention. Recovery indices compare reference windows, not matched individual outcomes or trust.\n\n'
    return {'docs/findings/analysis_04_monetization.md':doc4,'docs/findings/analysis_05_incident.md':doc5,
        'docs/findings/analysis_06_regional_strategy.md':doc6,'docs/sensitivity.md':docsen,
        'docs/verified_claims.md':header+'# Recomputed headline claims\n\nSource: the checked-in six CSVs. Rebuild with `python -m src.build_evidence`.\n\n'+table(pd.DataFrame(claims))+'\n'}


def main(check=False):
    for filename,content in render().items():
        path=project_root()/filename
        if check:
           if not path.exists() or path.read_text(encoding='utf-8') != content:
               raise ValueError(f'Stale evidence: {filename}')
           else:
               path.write_text(content, encoding='utf-8')
    print('Evidence documents match computed results' if check else 'Evidence documents regenerated')

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true')
    main(parser.parse_args().check)
