"""Render reviewed findings from computed results; --check detects stale documents."""
import argparse
from pathlib import Path
from src.analyze_game_data import load_data,project_root
from src.analyze_monetization import (prepare_sales,monetization_window_summary,bm_evaluation_summary,
    adjacent_product_summary,revenue_decomposition)
from src.analyze_incident import (incident_window_summary,incident_stage_evaluation,incident_retention_summary,
    incident_final_evaluation)
from src.analyze_lifecycle import event_dependency_summary,lifecycle_event_performance
from src.analyze_retention import retention_monthly_summary,regional_quality_summary,acquisition_quality_comparison
from src.analyze_pve import prepare_boss_funnel,boss_regional_summary,boss_performance_summary
from src.analyze_regional import regional_evidence_summary,regional_guardrail_matrix,regional_action_plan
from src.analyze_sensitivity import sensitivity_tables
import pandas as pd


def table(frame,columns=None):
    frame=frame[columns] if columns else frame
    def fmt(v):
        if pd.isna(v):return '—'
        if isinstance(v,float):return f'{v:,.2f}'
        return str(v).replace('|','/').replace('\n',' ')
    return '\n'.join(['| '+' | '.join(frame.columns)+' |','| '+' | '.join(['---']*len(frame.columns))+' |']+
        ['| '+' | '.join(fmt(v) for v in row)+' |' for row in frame.itertuples(index=False,name=None)])


def render():
    d,r,e,p,s,b=load_data(project_root());sales=prepare_sales(s,p)
    w=monetization_window_summary(d,sales);bm=bm_evaluation_summary(w,r)
    adj=adjacent_product_summary(d,sales);dec=revenue_decomposition(w)
    iw=incident_window_summary(d);st=incident_stage_evaluation(iw)
    ir=incident_retention_summary(r);final=incident_final_evaluation(st,ir)
    monthly=retention_monthly_summary(r,e);acq=acquisition_quality_comparison(r,monthly)
    boss=boss_performance_summary(prepare_boss_funnel(b,d))
    collab=pd.concat([regional_quality_summary(monthly,k) for k in ['fantasy_crossover_2024','astra_crossover_2025']])
    ev=regional_evidence_summary(event_dependency_summary(d),collab,boss_regional_summary(prepare_boss_funnel(b,d)),bm,final)
    guard=regional_guardrail_matrix(ev);actions=regional_action_plan(ev)
    payer,base=sensitivity_tables()
    bg=bm.set_index('scope').loc['ALL'];wg=w[w.scope.eq('ALL')]
    pre=wg.set_index('window').loc['local_baseline'];launch=wg.set_index('window').loc['launch']
    header='<!-- Generated by python -m src.build_evidence; edit the renderer, then regenerate. -->\n'
    doc4=header+f'''# Analysis 4: Revenue Growth and Subscription Value

## Decision

**{bg.outcome}.** Revenue per day rises {bg.launch_revenue_per_day_change_pct:.2f}% and
paying users per day rise {bg.launch_pu_per_day_change_pct:.2f}% around launch.
The new product supplies 25.47% of the arithmetic revenue increase, not a causal
incrementality estimate. Combined adjacent revenue per service payer-day changes
{bg.adjacent_launch_revenue_per_payer_day_change_pct:.2f}% at launch and
{bg.adjacent_post_14_revenue_per_payer_day_change_pct:.2f}% in the following 14 days.

## Measurement and source correction

The baseline is April 15–May 14, launch is May 15–June 14, and post-14 is
June 15–28, 2025. February is a secondary historical reference. The baseline
includes a content gap and recovery, so neither reference is an untreated control.
Compare daily amounts because the windows contain 30, 31 and 14 days.

The audit corrected service PU: it must lie between the maximum and sum of daily
product purchasers. The old independent target violated this in 1,302 date-region
rows. Sales and revenue are unchanged. PU is now a feasible synthetic union,
not reconstructed player identities.

| Metric | Local baseline | Launch |
|---|---:|---:|
| Paying users per day | {pre.pu_per_day:.2f} | {launch.pu_per_day:.2f} |
| DAU-weighted conversion (%) | {pre.conversion_rate*100:.2f} | {launch.conversion_rate*100:.2f} |
| Revenue per service payer-day (USD) | {pre.revenue_per_payer_day:.2f} | {launch.revenue_per_payer_day:.2f} |

Revenue per service payer-day uses sum(daily PU), not deduplicated monthly users
or purchasers of a specific offer. It is sensitive to the assumed buyer overlap.

## Revenue bridge

![Revenue bridge](../../images/bm_revenue_decomposition.png)

{table(dec)}

Revenue lift is chiefly a legacy-catalog rebound. Launch revenue is still
{abs(bg.launch_vs_february_revenue_per_day_change_pct):.2f}% below February.
Taxes, refunds, fees, acquisition cost and contribution margin are unobserved.

## Adjacent offers

![Adjacent offers](../../images/adjacent_product_cannibalization.png)

{table(adj,['product_name','launch_change_pct','post_14_change_pct','launch_warning','post_14_warning'])}

All three products cross the -5% warning during launch and post-14 under the
published payer assumption. Absolute combined adjacent revenue per day is still
{bg.adjacent_post_14_revenue_per_day_change_pct:.2f}% above baseline in post-14.
This is an allocation warning, not proof of an absolute revenue collapse or
same-buyer switching. Separate new-payer mix, purchase timing and buyer migration.

## Regional checks

![Regional checks](../../images/bm_regional_guardrails.png)

{table(bm,['scope','launch_revenue_per_day_change_pct','launch_pu_per_day_change_pct','adjacent_launch_revenue_per_payer_day_change_pct','adjacent_post_14_revenue_per_payer_day_change_pct','d30_change_pp'])}

**The previous JP-only launch warning is withdrawn.** Every region now crosses
the launch guardrail; Global West has the largest decline. Regional priorities
must follow corrected evidence, not an authored regional story.

## Robustness and next decision

[Baseline and payer-overlap sensitivity](../sensitivity.md) checks plausible
aggregate union assumptions. These are assumption scenarios, not confidence
intervals. Cross-product buyer identities are not identified by these inputs.
Do not remove an offer on this evidence. First instrument unique purchasers,
renewals and net spend; then randomize offer messaging with catalog-wide revenue
per eligible assigned user and retention guardrails. See [decision plan](../decision_plan.md).
'''
    stage=iw[iw.scope.eq('ALL')].copy();stage['revenue_per_payer_day_index']=stage['revenue_per_payer_day_recovery_index']
    ir_display=ir[ir.scope.eq('ALL')].copy()
    ir_display['d30_retention_pct']=ir_display.d30_retention*100
    doc5=header+f'''# Analysis 5: Incident and Recovery

## Decision

**Mixed: operational indices meet scenario thresholds; a new-cohort checkpoint gap remains.** The final September
21–30 window meets DAU ≥95, PU ≥90 and revenue ≥90 in every region.
Pooled October–November D30 is {final.set_index('scope').loc['ALL','d30_change_pp']:.2f} pp below June.
These are descriptive differences across cohorts, not an outage treatment effect.

## Stages and denominators

The operational reference is July 31–August 11 (12 days). June is the latest
complete monthly D30 reference before the incident. July overlaps the Astra
acquisition context and its follow-up crosses the outage; October includes an
autumn event. November provides a separate post-recovery check.

![Daily recovery](../../images/incident_daily_recovery_by_region.png)

{table(stage,['window_label','service_availability','dau_recovery_index','pu_recovery_index','revenue_recovery_index','returned_users_recovery_index','revenue_per_payer_day_index'])}

Index 100 means the reference value. Outage division by zero is undefined,
not zero conversion or ARPPU. Outflow is unobservable during the full shutdown.
Returned-user totals count daily reactivation, not unique compensation claimants.

![Commercial recovery](../../images/incident_reactivation_commercial_bridge.png)

Compensation returns reach 293.95% of baseline but revenue reaches 56.19%.
**After correcting impossible service PU, payers no longer recover ahead of
revenue in the remediation stage.** Both remain below their operational targets.
Activity indices return toward reference first; commercial indices are assessed separately. This does not measure individual recovery.

## Regional exit checks

![Regional exits](../../images/incident_regional_exit_guardrails.png)

{table(final,['scope','dau_recovery_index','pu_recovery_index','revenue_recovery_index','user_outflow_recovery_index','d30_change_pp','final_outcome'])}

Outflow is a secondary synthetic proxy, not a measured count of permanently lost
users. It is not a pass/fail condition. Global West has the largest D30 gap;
that does not imply the weakest technical restoration.

## Mature cohorts

![Mature cohorts](../../images/incident_d30_recovery_by_region.png)

{table(ir_display,['period_label','cohort_size','d30_retention_pct','d30_change_pp','d30_guardrail_failed'])}

Retention rates above are percentages; changes are percentage points. October and
November each fail the -0.5 pp rule in every region. These are **new acquisition
cohorts**, not the same pre-outage players: they cannot measure recovery of an
incident-exposed cohort or restored trust. Connect exposure, communication,
compensation claim, return and purchase at player level before testing mechanisms.

## Action

Exit the daily response phase only after the complete September window meets
all three targets. Continue acquisition-cohort monitoring separately. Establish
an exposed-player cohort for future incidents and a non-exposed comparison only
if its identification assumptions are credible. [Decision plan](../decision_plan.md).
'''
    doc6=header+'''# Analysis 6: Regional Decisions

## Decision

Use shared measurement and reversible tests, then prioritize regional diagnostics.
The original JP-only launch-warning claim is withdrawn after the payer audit:
all regions breach both launch and post-14 adjacent-offer guardrails. No composite
score combines revenue, retention points and participation indices.

## Evidence

![Regional evidence](../../images/regional_cross_analysis_evidence.png)

'''+table(ev,['region','fantasy_d30_change_pp','astra_d30_change_pp','astra_normal_participation_index','bm_launch_revenue_change_pct','bm_adjacent_launch_change_pct','bm_adjacent_post_14_change_pct','incident_nru_recovery_index','incident_d30_change_pp'])+'''

Within this synthetic comparison, KR has the lowest NRU reference index, so acquisition mix is an investigation
priority; channel causes and CAC are unobserved. JP has the largest Fantasy-context D30 checkpoint difference in this scenario, but no longer has a unique offer-warning mechanism. Global West
combines the strongest launch-revenue response with the largest launch adjacency
and later new-cohort D30 checkpoint gaps; additional spend should await quality diagnostics.

## Guardrails

![Guardrails](../../images/regional_guardrail_matrix.png)

'''+table(guard,['guardrail_label','region','value','status'])+'''

Equality semantics match source analyses: D30 at -1 pp and adjacency at -5%
are warnings; entry at 90 and residual D30 at -0.5 pp pass. Five checks warn in
all regions under the published payer assumption; daily operational exits pass.
These authored thresholds are not industry standards or statistical significance.

## Actions

'''+table(actions,['scope','priority','theme','action','evidence'])+'''

Low boss entry plus normal participant outcomes supports an entry hypothesis;
it does not locate individual dropout or rule out power-based selection.
Likewise, service-cohort D30 does not trace incident survivors. Follow the
[decision plan](../decision_plan.md), including telemetry, experimental unit,
primary outcome, guardrails and the decision that would change.
'''
    docsen=header+'''# Sensitivity to Baselines and Payer Assumptions

## Payer overlap is not identified

For each date-region, a feasible union lies between maximum(product purchasers)
and min(DAU, sum(product purchasers)). The published rule caps the original demand
target to that interval. Alternative extremes below are not estimates of real
buyer overlap. Even a feasible synthetic payer count does not validate behavior.

'''+table(payer,['scope','payer_assumption','launch_pu_per_day_change_pct','adjacent_launch_revenue_per_payer_day_change_pct','adjacent_post_14_revenue_per_payer_day_change_pct','outcome'])+'''

## Baseline choice changes magnitude

Seven, fourteen and twenty-eight day references are shown without silently
removing unfavorable event overlaps. Incident references end before the outage.
The primary operational baseline remains the 12 clean days in the specification.

'''+table(base,['context','baseline_days','baseline_start','baseline_end','overlaps','metric','change_pct'])+'''

These checks test stability under alternative assumptions. They are not causal
controls or uncertainty intervals. Generated rates were authored rather than
estimated from independent user observations, so inferential claims would add
false precision. A real deployment needs assignment/exposure logs, a planned
minimum detectable effect and dependence-aware analysis.
'''
    claims=[]
    def add(name,value):claims.append({'metric':name,'value':float(value)})
    life=lifecycle_event_performance(d,e);ann=life[life.event_name.eq('First Anniversary')].iloc[0]
    add('anniversary_dau_change_pct',ann.dau_during_change_pct)
    add('anniversary_post14_dau_change_pct',ann.dau_post_14_change_pct)
    for row in acq.itertuples():
        add(row.comparison_id+'_cohort_change_pct',row.cohort_size_change_pct)
        add(row.comparison_id+'_d30_change_pp',row.d30_retention_change_pp)
    add('astra_normal_participation_index',boss.query("boss_id=='BOSS004' and difficulty=='NORMAL'").participation_benchmark_index.iloc[0])
    add('subscription_revenue_change_pct',bg.launch_revenue_per_day_change_pct)
    add('subscription_pu_change_pct',bg.launch_pu_per_day_change_pct)
    add('adjacent_post14_change_pct',bg.adjacent_post_14_revenue_per_payer_day_change_pct)
    comp=iw.query("scope=='ALL' and window=='extraordinary_compensation'").iloc[0]
    add('compensation_returned_index',comp.returned_users_recovery_index)
    add('compensation_revenue_index',comp.revenue_recovery_index)
    add('residual_d30_change_pp',final.set_index('scope').loc['ALL','d30_change_pp'])
    scope = '\n> All figures are synthetic scenario comparisons. Legacy D30 means a nested checkpoint proxy, not session-based exact-day retention. Recovery indices compare reference windows, not matched individual outcomes or trust.\n\n'
    doc4 = doc4.replace('\n\n', '\n'+scope, 1)
    doc5 = doc5.replace('\n\n', '\n'+scope, 1)
    doc6 = doc6.replace('\n\n', '\n'+scope, 1)
    return {'docs/findings/analysis_04_monetization.md':doc4,'docs/findings/analysis_05_incident.md':doc5,
        'docs/findings/analysis_06_regional_strategy.md':doc6,'docs/sensitivity.md':docsen,
        'docs/verified_claims.md':header+'# Recomputed headline claims\n\nSource: the checked-in six CSVs. Rebuild with `python -m src.build_evidence`.\n\n'+table(pd.DataFrame(claims))+'\n'}


def main(check=False):
    for filename,content in render().items():
        path=project_root()/filename
        if check:
            if not path.exists() or path.read_text()!=content:raise ValueError(f'Stale evidence: {filename}')
        else:path.write_text(content)
    print('Evidence documents match computed results' if check else 'Evidence documents regenerated')

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true')
    main(parser.parse_args().check)
